package com.sample
 
import com.sample.DroolsTest.Message;
import java.util.List;
 
query "query fact count"
	Customer();
end


rule "rule1"
	salience 1
    when
        eval(true);
    then
        Customer cus = new Customer();
        cus.setName ("¿Ó2");
        cus.setAge(1);
        insert(cus);
        System.out.println("rule1---");
end
        

rule "rule2"
	#no-loop true
	salience 6
    when
        $customer:Customer(name == "¿Ó2" && age <10);
    then
    	Customer customer = new Customer();
    	customer.setName("¿Ó2");
    	customer.setAge($customer.getAge()+1);
        update(drools.getWorkingMemory().getFactHandleByIdentity($customer),customer);
        System.out.println("rule2--name:" + $customer.getName() + "   age:" + $customer.getAge());
end


